version: "3.8"

services:
    mysql:
        image: mysql:8.0
        container_name: concesionario_db
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root1234
            MYSQL_DATABASE: concesionario_jdr
            MYSQL_USER: concesionario
            MYSQL_PASSWORD: concesionario1234
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql
            - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
        networks:
            - concesionario_net

    app:
        build: .
        container_name: gescon_jdr
        restart: always
        ports:
            - "3000:3000"
        environment:
            DB_HOST: mysql
            DB_PORT: 3306
            DB_USER: concesionario
            DB_PASSWORD: concesionario1234
            DB_NAME: concesionario_db
            PORT: 3000
        depends_on:
            - mysql
        networks:
            - concesionario_net

volumes:
    mysql_data:

networks:
    concesionario_net:
